<?php
/**
* Ask a Librarian code
*/

function askalibrarian_node_view($node, $view_mode, $langcode) {
    drupal_add_js('(function() {
    var x = document.createElement("script"); x.type = "text/javascript"; x.async = true;
    x.src = (document.location.protocol === "https:" ? "https://" : "http://") + "ca.libraryh3lp.com/js/libraryh3lp.js?643";
    var y = document.getElementsByTagName("script")[0]; y.parentNode.insertBefore(x, y);
  })();',
        array(
            'type' => 'inline',
            'scope' => 'footer',
            'requires_jquery' => FALSE,
            'every_page' => TRUE)
    );
}

function askalibrarian_block_info() {
  // This example comes from node.module.
  $blocks['ask_a_librarian'] = array(
    'info' => t('Ask the library'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

function askalibrarian_block_view($delta = '') {
  // This example is adapted from node.module.
  $block['title'] = t('');
  $block['content'] = array(
    '#markup' => '<div class="needs-js">loading...</div>',
  );
  return $block;
}

