<?php
/**
* Ask a Librarian code
*/

function askalibrarian_node_view($node, $view_mode, $langcode) {
  if ($node->nid == 2610 or $node->nid == 3329) { //Looking for the specific node
    drupal_add_js(drupal_get_path('module', 'askalibrarian') . '/askalibrarian_head.js',
        array('type' => 'file', 'requires_jquery' => FALSE, 'every_page' => FALSE)
    );
  }
}

function askalibrarian_block_info() {
  // This example comes from node.module.
  $blocks['ask_a_librarian'] = array(
    'info' => t('Ask a librarian'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

function askalibrarian_block_view($delta = '') {
  return null;
}
